
# Default colors
[colors.primary]
background =  '#ffffea'
foreground =  '#000000'

[colors.normal]
black   = '#101010'
red     = '#af5f00'
green = "#396847"
yellow = "#ac5402"
blue = "#2848a9"
magenta = "#6e33ce"
cyan = "#287980"
white = "#f2e9e1"

[colors.bright]
black   = '#101010'
red     = '#af5f00'
green = "#577f63"
yellow = "#b86e28"
blue = "#4863b6"
magenta = "#8452d5"
cyan = "#488d93"
white = "#f4ece6"
