#!/bin/bash
brightness=`brightnessctl | grep -o "(.*" | tr -d "()"`
br_value=${brightness//%}
temp_line=
temp_indicator=
temp_indicator_placed=false
for i in {0..100..10}; do 
    if [ $i -ge $br_value ] && [ "$temp_indicator_placed" = false ]; then
        temp_indicator_placed=true
        line+=$temp_indicator
    else
        line+=$temp_line
    fi
done

if [ $br_value -lt 20 ]; then
	icon=''
elif [ $br_value -lt 60 ]; then
	icon=''
elif [ $br_value -le 100 ]; then
	icon=''
else
	icon=''
fi

echo "$icon  $line"
