#!/bin/bash
PACKAGE_ICON=
UPDATE=$(dnf check-update | awk '{print $1}' | grep [.] | wc -l)
PKG=$UPDATE/$(dnf list installed | wc -l)

(($UPDATE > 5)) && notify-send --app-name="Paketleme Yöneticisi" --category="Paket Yöneticisi" "Var $UPDATE güncellemeler mevcut." --icon="yazılım yöneticisi"
echo " $PACKAGE_ICON $PKG "
