#!/bin/bash
# panel-music.sh - Music Displayer
# @author umutsevdi 
#   A script that displays the song that is playing with 
# the singer's name 
# @requires playerctl

if ! command -v playerctl &> /dev/null ; then
    sudo dnf install playerctl
fi

stat=$(playerctl status -s 2>/dev/null)
artist="$(playerctl metadata artist -s)";
title=$(playerctl metadata title -s);
current="$artist - $title";

if [ "$stat" = "" ]; then
    echo
else
    echo "$play_pause  ${current:0:40}"
fi 
