#!/bin/bash
# panel-window.sh - Active panel displayer
# @author umutsevdi 
# An script that displays the focussed window.
# Designed to be used with topbars/menubars.
# @requires xdotool

if ! command -v xdotool &> /dev/null; then
    echo xdotool was not found
fi

title=`xdotool getwindowfocus getwindowname`

if [ -z "$title" ] && [ "$title" -ne "i3" ]; then
    title=`echo "$title" | tr "—" "-"`
    echo "$title"
fi
